#include QMK_KEYBOARD_H
enum custom_keycodes { SMTD_KEYCODES_BEGIN = SAFE_RANGE, CKC_A, CKC_S, CKC_D, CKC_F, CKC_Z, CKC_X, CKC_C, CKC_SPC, CKC_J, CKC_K, CKC_L, CKC_SCLN, CKC_COMM, CKC_DOT, CCA_SLSH, CKC_BSPC, SMTD_KEYCODES_END, M_GRV, M_TMUXSCR, M_CEH, M_ARROW };
